version: '3.8'
services:
  ffc-pay-statement-data:
    build:
      context: .
      target: production
    image: ffc-pay-statement-data
    container_name: ffc-pay-statement-data
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-pay-statement-data-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
