environment: development
environmentCode:
name: ffc-pay-statement-data
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-statement-data

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-statement-data-config-map

containerSecret:
  name: ffc-pay-statement-data-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReplicas: 1
  maxReplicas: 1
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0

container:
  imagePullPolicy: Always
  requestMemory: 150Mi
  requestCpu: 120m
  limitMemory: 150Mi
  limitCpu: 180m
  messageQueueHost: namespace.servicebus.windows.net
  dataTopicAddress: ffc-pay-statement-data

postgresService:
  postgresDb: ffc_pay_statement_data
  postgresqlHost: ffc-pay-statement-data-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
